# Generated by Django 3.0.5 on 2020-04-30 18:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('slug', models.CharField(choices=[('cardekho', 'Cardekho'), ('uber', 'Uber'), ('coverfox', 'Coverfox'), ('dealer', 'Dealer'), ('pos', 'Pos'), ('insurer', 'Insurer'), ('ola', 'Ola'), ('shopclues', 'Shopclues'), ('quickride', 'Quickride'), ('seeglob', 'Seeglob'), ('gaadikey', 'Gaadikey'), ('benefithub', 'Benefithub'), ('rsa365', 'Rsa365'), ('vasco', 'Vasco'), ('antilog', 'Antilog'), ('scripbox', 'Scripbox'), ('cims', 'Cims'), ('akoya', 'Akoya')], max_length=32, unique=True)),
                ('business_type', models.CharField(choices=[('cardekho', 'Cardekho'), ('uber', 'Uber'), ('coverfox', 'Coverfox'), ('dealer', 'Dealer'), ('pos', 'Pos'), ('insurer', 'Insurer'), ('ola', 'Ola'), ('shopclues', 'Shopclues'), ('quickride', 'Quickride'), ('seeglob', 'Seeglob'), ('gaadikey', 'Gaadikey'), ('benefithub', 'Benefithub'), ('rsa365', 'Rsa365'), ('vasco', 'Vasco'), ('antilog', 'Antilog'), ('scripbox', 'Scripbox'), ('cims', 'Cims'), ('akoya', 'Akoya')], max_length=32, null=True)),
                ('enable_subvariants_in_vehicle_master', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.AbstractBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
